name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'monorepo-subproject-1'
            split_repository: 'monorepo-subproject-1'
          - local_path: 'monorepo-subproject-2'
            split_repository: 'monorepo-subproject-2'

    steps:
      - uses: actions/checkout@v4

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.3"
        with:
          # ↓ split "packages/monorepo-subproject-1" directory
          package_directory: 'subprojects/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/oliverklee/monorepo-subproject-1 repository
          repository_organization: 'oliverklee'
          repository_name: '${{ matrix.package.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: "Oliver Klee (split bot)"
          user_email: "splitbot@oliverklee.de"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.3"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'subprojects/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/oliverklee/monorepo-subproject-1 repository
          repository_organization: 'oliverklee'
          repository_name: '${{ matrix.package.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: "Oliver Klee (split bot)"
          user_email: "splitbot@oliverklee.de"
